version: '3.9'
services:
  node:
    image: "node"
    working_dir: /home/node/app
    command: 
      - /bin/sh
      - '-c'
      - 'npm install && npm run start'
    ports:
      - '3001:3001'
    volumes:
      - './src:/home/node/app'